"""Restore curated deduplication state from a database backup.

Everything downstream of ``EnrichedEvents`` that the dedup v3 repair passes
curate lives in a small set of tables keyed on ``deduplicated_event_id``. Those
ids are regenerated by any full rebuild, so once a rebuild has run, the
ASD classifications, entity roles and merge membership that referenced the old
ids are unreachable - re-running the repair passes costs many LLM calls and
cannot be relied on to reproduce every earlier decision.

The upstream tables (``RawEvents``, ``EnrichedEvents``, ``EntitiesV2``, the
ledger tables) are untouched by a rebuild, so the curated state can be restored
by replacing only the dedup-derived tables with a backup's copy. Enriched events
added after the backup are then simply unmapped, and the next incremental
deduplication run merges them in the normal way.

This lives in the package rather than a one-off script so the recovery is
tested, has a dry run, and is idempotent: a second run reports zero changes.
"""

from __future__ import annotations

import logging
import sqlite3
from pathlib import Path
from typing import Dict, List, Union

logger = logging.getLogger(__name__)

# Parents before children, so inserts satisfy the foreign keys into
# DeduplicatedEvents; deletes run in the reverse order.
DEDUP_STATE_TABLES: List[str] = [
    "DeduplicatedEvents",
    "DeduplicationClusters",
    "DeduplicatedEventSources",
    "DeduplicatedEventEntities",
    "EventDeduplicationMap",
    "ASDRiskClassifications",
]

_BACKUP_ALIAS = "dedup_backup"


def _columns(conn: sqlite3.Connection, schema: str, table: str) -> List[str]:
    return [row[1] for row in conn.execute(f'PRAGMA {schema}.table_info("{table}")')]


def _count(conn: sqlite3.Connection, schema: str, table: str) -> int:
    return conn.execute(f'SELECT COUNT(*) FROM {schema}."{table}"').fetchone()[0]


def _differing_rows(conn: sqlite3.Connection, table: str) -> int:
    """Rows present on one side but not the other (symmetric difference)."""
    live_only = conn.execute(
        f'SELECT COUNT(*) FROM (SELECT * FROM main."{table}" '
        f'EXCEPT SELECT * FROM {_BACKUP_ALIAS}."{table}")'
    ).fetchone()[0]
    backup_only = conn.execute(
        f'SELECT COUNT(*) FROM (SELECT * FROM {_BACKUP_ALIAS}."{table}" '
        f'EXCEPT SELECT * FROM main."{table}")'
    ).fetchone()[0]
    return live_only + backup_only


def _unmapped_enriched_events(conn: sqlite3.Connection) -> int:
    """Active enriched events the next incremental dedup run will pick up."""
    return conn.execute(
        f"""
        SELECT COUNT(*) FROM main.EnrichedEvents ee
        WHERE ee.status = 'Active'
          AND NOT EXISTS (
              SELECT 1 FROM {_BACKUP_ALIAS}.EventDeduplicationMap edm
              WHERE edm.enriched_event_id = ee.enriched_event_id
          )
        """
    ).fetchone()[0]


def restore_dedup_state(
    conn: sqlite3.Connection,
    backup_path: Union[str, Path],
    dry_run: bool = True,
) -> Dict[str, object]:
    """Replace the dedup-derived tables in ``conn`` with the backup's copies.

    Args:
        conn: Connection to the live database.
        backup_path: SQLite backup holding the curated dedup state to restore.
        dry_run: Report what would change without writing (default True).

    Returns:
        ``{"tables": {table: {"live": n, "backup": n, "differing_rows": n}},
        "changed": bool, "applied": bool, "pending_incremental": n}`` where
        ``pending_incremental`` counts active enriched events that are not in
        the restored map and will be merged by the next incremental dedup run.

    Raises:
        FileNotFoundError: If the backup does not exist.
        ValueError: If a table is missing or its columns differ between the
            live database and the backup.
    """
    backup = Path(backup_path)
    if not backup.is_file():
        raise FileNotFoundError(f"backup not found: {backup}")

    conn.execute(f"ATTACH DATABASE ? AS {_BACKUP_ALIAS}", (str(backup),))
    try:
        tables: Dict[str, Dict[str, int]] = {}
        for table in DEDUP_STATE_TABLES:
            live_cols = _columns(conn, "main", table)
            backup_cols = _columns(conn, _BACKUP_ALIAS, table)
            if not live_cols or not backup_cols:
                raise ValueError(f"table {table} missing from live database or backup")
            if live_cols != backup_cols:
                raise ValueError(
                    f"column layout of {table} differs between live database and "
                    f"backup; refusing to restore ({live_cols} vs {backup_cols})"
                )
            tables[table] = {
                "live": _count(conn, "main", table),
                "backup": _count(conn, _BACKUP_ALIAS, table),
                "differing_rows": _differing_rows(conn, table),
            }

        changed = any(stats["differing_rows"] for stats in tables.values())
        report: Dict[str, object] = {
            "tables": tables,
            "changed": changed,
            "applied": False,
            "pending_incremental": _unmapped_enriched_events(conn),
        }
        if dry_run or not changed:
            return report

        try:
            conn.execute("BEGIN")
            for table in reversed(DEDUP_STATE_TABLES):
                conn.execute(f'DELETE FROM main."{table}"')
            for table in DEDUP_STATE_TABLES:
                conn.execute(
                    f'INSERT INTO main."{table}" SELECT * FROM {_BACKUP_ALIAS}."{table}"'
                )
            conn.commit()
        except Exception:
            conn.rollback()
            raise

        report["applied"] = True
        logger.info("Restored dedup state from %s: %s", backup,
                    {t: s["backup"] for t, s in tables.items()})
        return report
    finally:
        conn.execute(f"DETACH DATABASE {_BACKUP_ALIAS}")
